<footer>
	<div class="container">
		<a href="#" class="footer-logo"></a>
		<nav>
			<ul>
				<li><a href="#">Vásárlási tájékoztató</a></li>
				<li><a href="#">GY.I.K</a></li>
				<li><a href="#">ÁSZF</a></li>
				<li><a href="#">Kapcsolat</a></li>
			</ul>
		</nav>
		<div class="logo-wrapper">
			<a class="cib" href="#"></a>
			<a class="visa" href="#"></a>
			<a class="mastercard" href="#"></a>
		</div>
	</div>
</footer>
<!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
<script>
	(function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
	function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
	e=o.createElement(i);r=o.getElementsByTagName(i)[0];
	e.src='https://www.google-analytics.com/analytics.js';
	r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
	ga('create','UA-XXXXX-X','auto');ga('send','pageview');
</script>
</body>
</html>