<!DOCTYPE html>
<html lang="hu">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Web 2 print</title>
        <meta name="description" content="">
        <!-- Screen CSS -->
        <link href="/<?php echo $this->config->rootDir; ?>/<?php echo $this->system; ?>/view/<?php echo $this->config->template; ?>/css/screen.css" rel="stylesheet">
        <!-- 3rd-party CSS -->
        <link href='https://fonts.googleapis.com/css?family=Roboto:400,100,300,700&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <!-- Favicons -->
        <!-- JQuery -->
        <script src="/<?php echo $this->config->rootDir; ?>/<?php echo $this->system; ?>/view/<?php echo $this->config->template; ?>/js/3rd-party/jquery.min.js"></script>
        <!-- 3rd-party JS files -->
        
        <!-- Main JS file -->
        <script src="/<?php echo $this->config->rootDir; ?>/<?php echo $this->system; ?>/view/<?php echo $this->config->template; ?>/js/main.js"></script>
    </head>
    <body>
        <!--[if lt IE 9]>
        <p class="browserupgrade"><strong>Elavult</strong> böngészőt használsz. Kérlek <a href="http://browsehappy.com/">tölts le</a> újabb böngészőt, az optimális böngészés érdekében.</p>
        <![endif]-->
        <header>
            <div class="container">
                <a href="/" class="logo"></a>
                <button class="profile-icon"></button>
                <button class="nav-icon">
                    <span></span>
                    <span></span>
                    <span></span>
                </button>
                <nav></nav>
            </div>
        </header>